### PR TITLE
Add day-night-switch-button

### PR DESCRIPTION
**Pull request by Phillweston**

### CODE REVIEW

**Comment by Phillweston** [comment]
I've added the "day-night-switch-button" chapter, which is a good theme switch button for the website theme change.

**Comment by zxuqian** [comment]
Hi! Thanks for contributing! Only a minor problem. To add a new example to the homepage, 

1. Before doing any updates, run `yarn run watch` or `npm run watch`. This will automatically update the `index.js` file under the project root.
2. Update `src/index.js`. Add new example link and name at the top of `uis` array.
3. Add the `newItem: true` to the newly added item and remove it from the previous one.

**Comment by Phillweston** [comment]
Thanks for the instructions, I've changed the code and recommit it. Now it will be okay.

**Comment by zxuqian** [comment]
Merged.

**Pull request merged**
